name: API testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install pytest pytest-django pytest-pythonpath
        cd backend
        pip install -r requirements.txt

    - id: run_test
      name: Run flake8 and pytest
      env:
        SECRET_KEY: "${{ secrets.SECRET_KEY }}"
        DEBUG: "${{ secrets.DEBUG }}"
      run: |
        python -m flake8
        cd backend
        python manage.py makemigrations
        python manage.py migrate
        pytest

    - name: Check on failures
      if: ${{ failure() && steps.run_test.conclusion == 'failure' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Ошибка при тестировании - ${{ github.repository }}
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}